language: c
env:
  matrix:
  - MONO_PREFIX="/opt/mono-3" MONO_GAC_PREFIX="/opt/mono-3" LD_LIBRARY_PATH="/opt/mono-3/lib"
    C_INCLUDE_PATH="/opt/mono-3/include" ACLOCAL_PATH="/opt/mono-3/share/aclocal"
    PKG_CONFIG_PATH="/opt/mono-3/lib/pkg-config:$PKG_CONFIG_PATH" PATH="/opt/mono-3/bin:$PATH"
  global:
    secure: Djv46BMsg1IkFlZsqef7TyKeylNHc7MUVcDYL1Ld8Ldf5osRxgk0DISFzPlbFL8NvlLBI/VXXHWt4yOmiAjaJJ8NMnhn+5jg8JGDT/kJQZAGFnvdULQsfwo8tc4ziP5sk+Fg2Mo9w7ZvJm5qqa+gHYQlzaISEOLfdLOLoNB0ACY=
before_install:
- sudo add-apt-repository ppa:keks9n/monodevelop-latest -y
- sudo apt-get update -qq -y
- sudo apt-get install mono-3-opt monodevelop-latest git automake autoconf m4
script:
- mono --version
- mozroots --import --sync
- make
- make test CONFIGURATION=UnitTesting
